### ISSUE TITLE
Has the sampling matrix been made public

### ISSUE THREAD

**Issue by jingyaogong** [ICSResearch/CPP-Net#1]
I'm interested in this method. Where do the numpy-formatted sampling rate matrices for `sampling_matrix` come from? 

I seem to not find it in any comments or files, which prevents me from performing performance tests on the method.

Feel free to let me know of any new developments. Thank you!

**Comment by ICSResearch** [comment]
We have uploaded the numpy file for sampling_matrix and updated the load path in CPP.py. Thank you for bringing this to our attention!
